channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - rise
  - mongodb
  - seaborn
  - pip:
    - git+https://github.com/IDSIA/sacred.git
    - incense